### ISSUE TITLE
SplFileInfo::getSize(): stat failed for /home2/bintankab/simonev-api/storage/app/exported/forma_b_2020-05-04_10_05_56.xlsx 

### ISSUE THREAD

**Issue by mrizkir** [mrizkir/simonev-api#5]
[2020-05-04 10:47:57] production.ERROR: RuntimeException: SplFileInfo::getSize(): stat failed for /home2/bintankab/simonev-api/storage/app/exported/forma_b_2020-05-04_10_05_56.xlsx in /home2/bintankab/simonev-api/vendor/symfony/http-foundation/BinaryFileResponse.php:200
Stack trace:
#0 /home2/bintankab/simonev-api/vendor/symfony/http-foundation/BinaryFileResponse.php(200): SplFileInfo->getSize()
#1 /home2/bintankab/simonev-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(438): Symfony\Component\HttpFoundation\BinaryFileResponse->prepare(Object(Illuminate\Http\Request))
#2 /home2/bintankab/simonev-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(133): Laravel\Lumen\Application->prepareResponse(Object(Symfony\Component\HttpFoundation\BinaryFileResponse))
#3 /home2/bintankab/simonev-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(117): Laravel\Lumen\Application->callTerminableMiddleware(Object(Symfony\Component\HttpFoundation\BinaryFileResponse))
#4 /home2/bintankab/simonev-api/public/index.php(28): Laravel\Lumen\Application->run()
#5 {main} {"exception":"[object] (RuntimeException(code: 0): SplFileInfo::getSize(): stat failed for /home2/bintankab/simonev-api/storage/app/exported/forma_b_2020-05-04_10_05_56.xlsx at /home2/bintankab/simonev-api/vendor/symfony/http-foundation/BinaryFileResponse.php:200)
[stacktrace]
#0 /home2/bintankab/simonev-api/vendor/symfony/http-foundation/BinaryFileResponse.php(200): SplFileInfo->getSize()
#1 /home2/bintankab/simonev-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(438): Symfony\\Component\\HttpFoundation\\BinaryFileResponse->prepare(Object(Illuminate\\Http\\Request))
#2 /home2/bintankab/simonev-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(133): Laravel\\Lumen\\Application->prepareResponse(Object(Symfony\\Component\\HttpFoundation\\BinaryFileResponse))
#3 /home2/bintankab/simonev-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(117): Laravel\\Lumen\\Application->callTerminableMiddleware(Object(Symfony\\Component\\HttpFoundation\\BinaryFileResponse))
#4 /home2/bintankab/simonev-api/public/index.php(28): Laravel\\Lumen\\Application->run()
#5 {main}

**Comment by mrizkir** [comment]
refer to [this](https://github.com/laravel/lumen-framework/issues/523)

**Comment by mrizkir** [comment]
solution: try [this](https://github.com/Maatwebsite/Laravel-Excel/issues/2281)
